CREATE TABLE IF NOT EXISTS `characters` (
  `account_name` VARCHAR(12) NOT NULL,
  `obj_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `char_name` VARCHAR(12) NOT NULL,
  `realm_level` INT NOT NULL DEFAULT 1 COMMENT '境界內小等級 1~10',
  `sex` TINYINT NOT NULL DEFAULT 0 COMMENT '0=男 1=女',
  `attribute` TINYINT NOT NULL DEFAULT 0 COMMENT '靈根 0=金 1=木 2=水 3=火 4=土 5=風 6=雷',
  `natal_weapon_id` TINYINT NOT NULL DEFAULT 0 COMMENT '本命攻擊法寶武器類型',
  `stats_intel` INT NOT NULL DEFAULT 10,
  `stats_spirit` INT NOT NULL DEFAULT 10,
  `stats_agility` INT NOT NULL DEFAULT 10,
  `stats_constitution` INT NOT NULL DEFAULT 10,
  `map_id` INT NOT NULL DEFAULT 0,
  `loc_x` INT NOT NULL DEFAULT 0,
  `loc_y` INT NOT NULL DEFAULT 0,
  `current_hp` INT NOT NULL DEFAULT 0,
  `max_hp` INT NOT NULL DEFAULT 0,
  `current_mp` INT NOT NULL DEFAULT 0,
  `max_mp` INT NOT NULL DEFAULT 0,
  `defense` INT NOT NULL DEFAULT 0,
  `attack` INT NOT NULL DEFAULT 0,
  `hit` INT NOT NULL DEFAULT 0,
  `dodge` INT NOT NULL DEFAULT 0,
  `hp_regen` INT NOT NULL DEFAULT 0,
  `mp_regen` INT NOT NULL DEFAULT 0,
  `puppet_max` INT NOT NULL DEFAULT 0,
  `spell_learn_rate` INT NOT NULL DEFAULT 100,
  `craft_proficiency_rate` INT NOT NULL DEFAULT 100,
  `exp` INT NOT NULL DEFAULT 0,
  `realm_stage` TINYINT NOT NULL DEFAULT 0 COMMENT '境界階段，0=鍛體期',
  `faction` VARCHAR(24) NOT NULL DEFAULT '' COMMENT '勢力',
  `life_job` VARCHAR(24) NOT NULL DEFAULT '' COMMENT '生活職業',
  `life_job_level` INT NOT NULL DEFAULT 0,
  `core_technique` VARCHAR(24) NOT NULL DEFAULT '' COMMENT '核心功法',
  PRIMARY KEY (`account_name`, `char_name`),
  UNIQUE KEY `uk_obj_id` (`obj_id`),
  UNIQUE KEY `uk_char_name` (`char_name`),
  KEY `idx_account_name` (`account_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
